name: Publicar en GitBook

on:
  push:
    branches:
      - main
      - 'releases/**'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    env:
      VERSION: ${{ github.event.release.tag_name }}
      GITBOOK_SPACE: "lDjUpn42IqZ3iP1cWWjX"
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Publish to GitBook
        env:
          UPLOAD_URL: ${{ github.event.repository.html_url }}/gh-pages/release-notes.md
        run: |
          JSON_PAYLOAD=$(printf '{"source": "%s", "title": "Release v%s", "emoji": "1f389", "visibility": "public", "editMode": "live"}' "$UPLOAD_URL" "${{ github.event.release.tag_name }}")
          curl -v -X POST "https://api.gitbook.com/v1/spaces/${{ env.GITBOOK_SPACE }}/content/import" \
            -H "Authorization: Bearer ${{ secrets.GITBOOK_API_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d "$JSON_PAYLOAD"

      - name: Configure Git Identity
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Prepare gh-pages Branch
        run: |
          git fetch origin gh-pages || git checkout --orphan gh-pages
          git checkout gh-pages

      - name: Generate Release Notes
        run: |
          echo "# Release ${{ github.event.release.tag_name }}" > release-notes.md
          # Add more content to release-notes.md as needed
      - name: Verificar contenido de gh-pages
        run:
          git ls-tree -r gh-pages

      - name: Commit and Push Changes
        run: |
          git add release-notes.md
          git commit -m "Publish Release ${{ github.event.release.tag_name }}"
          git push origin gh-pages

      - name: Depurar variables
        run: |
          echo "Repositorio: ${{github.repository}}"
          echo "Nomre de la etiqueta: ${{github.event.release.tag_name}}"

      - name: Publish to GitBook
        env:
          UPLOAD_URL: "https://raw.githubusercontent.com/${{ github.repository }}/gh-pages/release-notes.md"
        run: |
          JSON_PAYLOAD=$(printf '{"source": "%s", "title": "Release v%s", "emoji": "1f389", "visibility": "public", "editMode": "live"}' "$UPLOAD_URL" "${{ github.event.release.tag_name }}")
          curl -v -X POST "https://api.gitbook.com/v1/spaces/${{ env.GITBOOK_SPACE }}/content/import" \
            -H "Authorization: Bearer ${{ secrets.GITBOOK_API_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d "$JSON_PAYLOAD"

      - name: Confirm Success
        run: |
          echo "Release ${{ github.event.release.tag_name }} published to GitBook with URL: ${{ env.UPLOAD_URL }}"