name: Publicar en GitBook

on:
  workflow_run:
    workflows:
      - Versionado # Nombre del flujo que activa este (el `name` de versionado.yml)
    types:
      - completed # Se activa cuando el flujo de "versionado" termina
jobs:
  publish:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write # Permisos necesarios para modificar la rama gh-pages
      issues: write
      pull-requests: write

    env:
      VERSION: ${{ github.event.release.tag_name }}
      UPLOAD_URL: https://raw.githubusercontent.com/${{ github.repository }}/gh-pages/${{ github.event.release.tag_name }}.md
      GIT_USER_NAME: "Ronald Pelaez"
      GIT_USER_EMAIL: "ronaldpelaez201@gmail.com"

    steps:
      - name: Configure Git Identity
        run: |
          git config --global user.name "${GIT_USER_NAME}"
          git config --global user.email "${GIT_USER_EMAIL}"

      - name: Clone Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Prepare gh-pages Branch
        run: |
          git fetch origin gh-pages || git checkout --orphan gh-pages
          git checkout gh-pages
          git reset --hard

      - name: Move Release Notes
        run: |
          mkdir -p releases
          mv releases/${VERSION}.md .

      - name: Commit and Push Changes
        run: |
          git add ${VERSION}.md
          git commit -m "Añadir notas del release ${VERSION}"
          git push origin gh-pages

      - name: Set Uploaded File URL
        run: echo "UPLOAD_URL=${UPLOAD_URL}" >> $GITHUB_ENV

      - name: Publish to GitBook
        run: |
          curl -X POST "https://api.gitbook.com/v1/spaces/lDjUpn42IqZ3iP1cWWjX/content/import" \
          -H "Authorization: Bearer ${{ secrets.GITBOOK_API_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d '{
            "source": "'"${UPLOAD_URL}"'",
            "title": "Release v'"${VERSION}"'",
            "emoji": "1f389",
            "visibility": "public",
            "editMode": "live"
          }'

      - name: Confirm Success
        run: |
          echo "Release ${VERSION} publicado en GitBook con URL: ${UPLOAD_URL}"