name: Publicar en GitBook

on:
  workflow_run:
    workflows:
      - Versionado # Nombre del flujo que activa este (el `name` de versionado.yml)
    types:
      - completed # Se activa cuando el flujo de "versionado" termina
jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Configurar identidad de Git
        run: |
          git config --global user.name "Ronald Pelaez"
          git config --global user.email "ronaldpelaez201@gmail.com"

      - name: Clonar el repositorio
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cambiar a la rama gh-pages
        run: |
          # Crear la rama gh-pages si no existe
          git fetch origin gh-pages || git checkout --orphan gh-pages
          git checkout gh-pages
          git reset --hard

      - name: Mover las notas del release
        env:
          VERSION: ${{ github.event.release.tag_name }}
        run: |
          mkdir -p releases
          mv releases/${VERSION}.md .

      - name: Confirmar y enviar los cambios
        env:
          VERSION: ${{ github.event.release.tag_name }}
        run: |
          git add ${VERSION}.md
          git commit -m "Añadir notas del release ${VERSION}"
          git push origin gh-pages

      - name: Generar la URL del archivo subido
        env:
          VERSION: ${{ github.event.release.tag_name }}
        run: |
          UPLOAD_URL="https://raw.githubusercontent.com/${{ github.repository }}/gh-pages/${VERSION}.md"
          echo "Archivo subido a: ${UPLOAD_URL}"
          echo "UPLOAD_URL=${UPLOAD_URL}" >> $GITHUB_ENV

      - name: Publicar en GitBook
        env:
          GITBOOK_API_TOKEN: ${{ secrets.GITBOOK_API_TOKEN }}
        run: |
          curl -X POST "https://api.gitbook.com/v1/spaces/lDjUpn42IqZ3iP1cWWjX/content/import" \
          -H "Authorization: Bearer $GITBOOK_API_TOKEN" \
          -H "Content-Type: application/json" \
          -d '{
            "source": "'"${UPLOAD_URL}"'",
            "title": "Release v'"${VERSION}"'",
            "emoji": "1f389",
            "visibility": "public",
            "editMode": "live"
          }'
