name: Release to GitBook

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21'

      - name: Install dependencies
        run: |
          npm install

      - name: Run semantic-release
        run: |
          npx semantic-release

      - name: Publish to GitBook
        run: |
          curl -X POST https://api.gitbook.com/spaces/${{ secrets.GITBOOK_SPACE_ID }}/content \
          -H "Authorization: Bearer ${{ secrets.GITBOOK_API_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d '{
            "type": "commit",
            "message": "New release ${GITHUB_REF}",
            "content": "This is the content from the release.",
            "parent_id": "root"
          }'
