name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    permissions:
      contents: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: actions/setup-node@v4
        with:
          node-version: 21
      - run: npm ci
      - run: npm run build
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  sync-with-gitbook:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Sincronizar con GitBook
        env:
          GITBOOK_API_KEY: ${{ gb_api_5uQSr4OS3ED4d6UsyUhYFQu894Xs2P9uypr6fRDd }}
        run: |
          curl -X POST "https://api.gitbook.com/v1/spaces/<lDjUpn42IqZ3iP1cWWjX>/content" \
          -H "Authorization: Bearer $GITBOOK_API_KEY" \
          -H "Content-Type: application/json" \
          -d '{
                "title": "Changelog",
                "content": "'"$(cat CHANGELOG.md | jq -Rs .)"'"
              }'
