on: # Activa el flujo de trabajo
  push: # Determina que el flujo de trabajo se activar치 solo cuando se haga push
    branches:
      - 'main' # Indica que solo se activar치 con la rama main

jobs:
  release:
    runs-on: ubuntu-latest # Sistema en el que se ejecutar치 el workflow (recomendado)

    permissions: # Permisos para que el workflow realice las funciones necesarias
      contents: write
      issues: write
      pull-requests: write
      id-token: write

    steps:
      - name: Check out repository # Clona el repositorio
        uses: actions/checkout@v4

      - name: Set up Node.js # Configura Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '21' # Versi칩n de Node.js a utilizar

      - name: Install dependencies # Instala las dependencias necesarias
        run: npm install

      - name: Run semantic-release # Ejecuta semantic-release
        run: npx semantic-release
        env: # Define las variables de entorno necesarias
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN1 }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
