name: Release to GitBook

on:
  push:
    tags:
      - 'v*.*.*'
    branches:
      - 'main'

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '21'

      - name: Install dependencies
        run: |
          npm install

      - name: Run semantic-release
        run: |
          npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to GitBook
        run: |
          VERSION=$(echo "${GITHUB_REF}" | sed 's/refs\/tags\///')

          curl -X POST "https://api.gitbook.com/v1/spaces/lDjUpn42IqZ3iP1cWWjX/content/import" \
          -H "Authorization: Bearer ${{ secrets.GITBOOK_API_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d '{
            "title": "Release v'"${VERSION}"'",
            "emoji": "1f389",
            "visibility": "public",
            "editMode": "live",
            "description": "Release content for version v'"${VERSION}"'"
          }'

      - name: Debug output
        run: |
          echo "Published version ${VERSION} to GitBook."
