name: Release to GitBook

on:
  push:
    tags:
      - 'v*.*.*'
    branches:
      - 'main'

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      issues: write
      pull-requests: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '21'

      - name: Install dependencies
        run: |
          npm ci  

      - name: Run semantic-release
        run: |
          npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to GitBook
        run: |
          
          VERSION=$(echo "${GITHUB_REF}" | sed 's/refs\/tags\///')

         
          curl -X PATCH "https://api.gitbook.com/v1/spaces/lDjUpn42IqZ3iP1cWWjX" \
          -H "Authorization: Bearer ${{ secrets.GITBOOK_API_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d '{
            "message": "New release version ${VERSION}",
            "content": "This release version includes new updates for version ${VERSION}."
          }'