name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    permissions:
      contents: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: actions/setup-node@v4
        with:
          node-version: 21
      - run: npm ci
      - run: npm run build
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GB_API_KEY: ${{ secrets.GB_API_KEY }}  # Tu API Key de GitBook
          GB_SPACE_ID: ${{ secrets.GB_SPACE_ID }} # El ID de tu espacio en GitBook

      # Paso para subir el changelog.md a GitBook
      - name: Upload changelog to GitBook
        run: |
          # Definir la URL y los encabezados de la API de GitBook
          url="https://api.gitbook.com/v1/spaces/${{ secrets.GB_SPACE_ID }}/content"
          headers="Authorization: Bearer ${{ secrets.GB_API_KEY }}"
          content=""

          # Obtener el contenido del archivo CHANGELOG.md
          content=$(cat CHANGELOG.md)

          # Crear el cuerpo de la solicitud para GitBook
          json_data=$(jq -n \
            --arg title "Changelog" \
            --arg content "$content" \
            '{title: $title, content: $content}')

          # Enviar la solicitud POST a la API de GitBook para crear o actualizar el contenido
          curl -X POST "$url" \
            -H "$headers" \
            -H "Content-Type: application/json" \
            -d "$json_data"
        env:
          GB_API_KEY: ${{ secrets.GB_API_KEY }}
          GB_SPACE_ID: ${{ secrets.GB_SPACE_ID }}
